### ISSUE TITLE
When I want to use optimismSDK.CrossChainMessenger, I get exception

### ISSUE THREAD

**Issue by Murphy-hub** [bnb-chain/opbnb-docs#47]
Use the tutorial link: 
https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge-erc20

Chain :
const l1Url = `https://data-seed-prebsc-1-s1.bnbchain.org:8545`
const l2Url = `https://opbnb-testnet-rpc.bnbchain.org`

Log:
```
Error: cannot get contract AddressManager for unknown L2 chain ID 5611, you must provide an address
    at getOEContract (/Users/zhangshuai/web3/optimism-tutorial/cross-dom-bridge-erc20/node_modules/@eth-optimism/sdk/dist/utils/contracts.js:19:15)
    at getAllOEContracts (/Users/zhangshuai/web3/optimism-tutorial/cross-dom-bridge-erc20/node_modules/@eth-optimism/sdk/dist/utils/contracts.js:49:63)
    at new CrossChainMessenger (/Users/zhangshuai/web3/optimism-tutorial/cross-dom-bridge-erc20/node_modules/@eth-optimism/sdk/dist/cross-chain-messenger.js:208:56)
    at setup (/Users/zhangshuai/web3/optimism-tutorial/cross-dom-bridge-erc20/index.js:74:25)
    at async main (/Users/zhangshuai/web3/optimism-tutorial/cross-dom-bridge-erc20/index.js:180:5)
```

I can't find the AddressManager contract address in the docs

**Comment by CocoStarZ** [comment]
What do you want achieve? for cross-layer communication, you can refer to this:
https://docs.bnbchain.org/opbnb-docs/docs/faq/protocol-faqs#how-to-allow-smart-contract-cross-chain-communication-between-l1-and-l2

**Comment by Murphy-hub** [comment]
@CocoStarZ  I want to use eth-optimism/sdk to bridge L1 ERC20 Token to L2.
According to the Op [cross-dom-bridge-erc20](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/cross-dom-bridge-erc20) tutorial, it is achievable on the op Goerli testnet, but there is an exception on the OPBNB testnet

**Comment by huihzhao** [comment]
@Murphy-hub This is a known issue, you need configure the chainid and other corresponding configurations when you create a crosschainMessenger like below.

crossChainMessenger = new optimismSDK.CrossChainMessenger({
      // l1ChainId: 5,    // Goerli value, 1 for mainnet
      // l2ChainId: 420,  // Goerli value, 10 for mainnet
      l1ChainId: 97,    // BSC testnet
      l2ChainId: 5611,  // opbnb testnet
      l1SignerOrProvider: l1Signer,
      l2SignerOrProvider: l2Signer,
      bedrock: true,
      contracts: {
        l1: {
          "AddressManager": "0x0000000000000000000000000000000000000000",
          "StateCommitmentChain": "0x0000000000000000000000000000000000000000",
          "CanonicalTransactionChain": "0x0000000000000000000000000000000000000000",
          "BondManager": "0x0000000000000000000000000000000000000000",
          "L1CrossDomainMessenger": "0xD506952e78eeCd5d4424B1990a0c99B1568E7c2C",
          "L1StandardBridge": "0x677311Fd2cCc511Bbc0f581E8d9a07B033D5E840",
          "OptimismPortal": "0x4386C8ABf2009aC0c263462Da568DD9d46e52a31",
          "L2OutputOracle": "0xFf2394Bb843012562f4349C6632a0EcB92fC8810"
        },
        l2: optimismSDK.DEFAULT_L2_CONTRACT_ADDRESSES,
      }
  })

**Comment by Murphy-hub** [comment]
> @Murphy-hub This is a known issue, you need configure the chainid and other corresponding configurations when you create a crosschainMessenger like below.
> 
> crossChainMessenger = new optimismSDK.CrossChainMessenger({ // l1ChainId: 5, // Goerli value, 1 for mainnet // l2ChainId: 420, // Goerli value, 10 for mainnet l1ChainId: 97, // BSC testnet l2ChainId: 5611, // opbnb testnet l1SignerOrProvider: l1Signer, l2SignerOrProvider: l2Signer, bedrock: true, contracts: { l1: { "AddressManager": "0x0000000000000000000000000000000000000000", "StateCommitmentChain": "0x0000000000000000000000000000000000000000", "CanonicalTransactionChain": "0x0000000000000000000000000000000000000000", "BondManager": "0x0000000000000000000000000000000000000000", "L1CrossDomainMessenger": "0xD506952e78eeCd5d4424B1990a0c99B1568E7c2C", "L1StandardBridge": "0x677311Fd2cCc511Bbc0f581E8d9a07B033D5E840", "OptimismPortal": "0x4386C8ABf2009aC0c263462Da568DD9d46e52a31", "L2OutputOracle": "0xFf2394Bb843012562f4349C6632a0EcB92fC8810" }, l2: optimismSDK.DEFAULT_L2_CONTRACT_ADDRESSES, } })

Nice, it works

**Comment by Murphy-hub** [comment]
> @Murphy-hub This is a known issue, you need configure the chainid and other corresponding configurations when you create a crosschainMessenger like below.
> 
> crossChainMessenger = new optimismSDK.CrossChainMessenger({ // l1ChainId: 5, // Goerli value, 1 for mainnet // l2ChainId: 420, // Goerli value, 10 for mainnet l1ChainId: 97, // BSC testnet l2ChainId: 5611, // opbnb testnet l1SignerOrProvider: l1Signer, l2SignerOrProvider: l2Signer, bedrock: true, contracts: { l1: { "AddressManager": "0x0000000000000000000000000000000000000000", "StateCommitmentChain": "0x0000000000000000000000000000000000000000", "CanonicalTransactionChain": "0x0000000000000000000000000000000000000000", "BondManager": "0x0000000000000000000000000000000000000000", "L1CrossDomainMessenger": "0xD506952e78eeCd5d4424B1990a0c99B1568E7c2C", "L1StandardBridge": "0x677311Fd2cCc511Bbc0f581E8d9a07B033D5E840", "OptimismPortal": "0x4386C8ABf2009aC0c263462Da568DD9d46e52a31", "L2OutputOracle": "0xFf2394Bb843012562f4349C6632a0EcB92fC8810" }, l2: optimismSDK.DEFAULT_L2_CONTRACT_ADDRESSES, } })

Nice, it works
