### ISSUE TITLE
Safe | Transaction Service API

### ISSUE THREAD

**Issue by tenbits** [bnb-chain/opbnb-docs#90]
Hi Team,

It is not listed here - [multisig-wallet.md](https://github.com/bnb-chain/opbnb-docs/blob/80f5733a8661bb7d003f1883c9aa70f60c15da18/docs/build-on-opbnb/multisig-wallet.md), but there should also be a link to the Safe **Transaction Service** API, something like https://safe-transaction-bsc.safe.global/ but for opBNB?

Thanks

**Comment by huihzhao** [comment]
@tenbits sorry for the confusion, but I still do not understand what you mean here. could you elaborate more about your request? thanks

**Comment by tenbits** [comment]
The {Gnosis} Safe infrastructure should contain also the **Transaction Service API**: 

- https://docs.safe.global/safe-core-api/service-architecture/safe-transaction-service 
- https://github.com/safe-global/safe-transaction-service

Transaction Service (**Tx Service**) is the core part of the infrastructure:
https://github.com/safe-global/safe-infrastructure/tree/746a8c052a1b588c3f4f7a59c630e9690d246478

![image](https://github.com/bnb-chain/opbnb-docs/assets/550353/a6d01639-bb23-4841-9d14-433b8fcae1f8)


In particular, I would like to create/list safe transactions programmatically by using [@safe-global/api-kit](https://www.npmjs.com/package/@safe-global/api-kit)  It requires the **Transaction Service API** URL.

**Comment by welkin22** [comment]
Hello @tenbits, the address of the Testnet is: https://safe-transaction-opbnb-testnet.bnbchain.org/ The Mainnet network one is not yet deployed, once it is ready, I will update it here.

**Comment by welkin22** [comment]
Mainnet network is: https://safe-transaction-opbnb-mainnet.bnbchain.org/

**Comment by welkin22** [comment]
Address has been provided, I will close this issue for now. Feel free to ask again if you have any further questions.
